name: Test content

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: "0 12 * * 0-6"

jobs:
  build:
    name: Test deploy
    runs-on: ubuntu-latest

    steps:
    - uses: drudzikatlassian/test-action@v0.0.1-alpha
    - name: Test a one-line script
